# Generated by Django 5.1.5 on 2025-01-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('milage', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
