# Generated by Django 5.1.5 on 2025-01-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listings',
            new_name='Listing',
        ),
    ]
