# Generated by Django 5.1.5 on 2025-01-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='vehicles/default.jpg', upload_to='vehicles/'),
        ),
    ]
