# Generated by Django 5.1.5 on 2025-01-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_brand_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='milage',
            new_name='mileage',
        ),
    ]
